### ISSUE TITLE
VS Code extension improvements

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1647]
Epic to track the next round of improvements for the VS Code extension

**Comment by molant** [comment]
Current action item is to start ideating new features.

**Comment by molant** [comment]
I'm thinking we should remove the option to install webhint globally when not found. It only produces headaches. What do you think?

/cc @antross

**Comment by antross** [comment]
I agree installing to a project is best - should we do something similar for the CLI guidance? [Current documentation](https://webhint.io/docs/user-guide/) still suggests to make that a global install as well.
```
npm install -g --engine-strict hint
```

**Comment by molant** [comment]
Yup

**Comment by molant** [comment]
Looks like we are already refreshing on `.hintrc` changes so we should do the same with `package.json` 😊

**Comment by antross** [comment]
IIRC we tried to tackle `package.json` when refreshing for `.hintrc`, but the data was getting cached internally so the results didn't change. We may have fixed that now since we later did work to bypass the `require` cache when reloading (in which case this should be an easy update).

**Comment by molant** [comment]
I'm preparing a demo of the VS Code extension and when I change the property `borwserslists` I have to manually reload VS Code 😕

**Comment by antross** [comment]
Editing [`src/extension.ts`](https://github.com/webhintio/hint/blob/master/packages/extension-vscode/src/extension.ts#L44) and changing
```ts
            // Notify the server if a webhint-related configuration changes.
            fileEvents: workspace.createFileSystemWatcher('**/.hintrc')
```
to
```ts
            // Notify the server if a webhint-related configuration changes.
            fileEvents: [
                workspace.createFileSystemWatcher('**/.hintrc'),
                workspace.createFileSystemWatcher('**/package.json')
            ]
```
should do the trick if we fixed the caching issue (haven't tested it yet, though).

**Comment by molant** [comment]
Another thing we should do is to improve when we are prompting to the user.

* If there's no `.hintrc` file and `hint` is nowhere in `package.json` we shouldn't prompt anything
* All other cases should probably remain the same

**Comment by molant** [comment]
> should do the trick if we fixed the caching issue (haven't tested it yet, though).

I just tried it and I think we still have the caching issue 😞

**Comment by hxlnt** [comment]
Looks like the specific fixes listed here have been fixed; closing for now.
